### ISSUE TITLE
Can't get it to work in FF30

### ISSUE THREAD

**Issue by FunkSugar** [is-already-taken/firecompass#5]
I had this working great in win vista - not sure what the version of ff was unforunately, I just upgraded my OS to win 8.1 and reinstalled FF30, FB 2.0.1 and FC 0.2 and I can't see the sass line numbers.

I installed ruby in the new OS, but pointed it to the previously used collection of gems and files (the work/ruby config etc was on a separate drive not formatted during upgrade - compass is compiling fine using the old settings)

Sorry - more info - the comment lines don't seem to be adding to the css file since re-install... but the config.rb file is the same as it was before reinstall... 

 environment = :development
 firesass = true

seems i'm getting mixed up between firesass (seems to be removed) and firecompass
I definitely have firesass installed.

is it normall for css files to have this above every line? it's my first time using SASS sorry for n00biness:
@media -sass-debug-info{filename{font-family:file:\/\/M:\/wamp\/www\/Tandem\/sites\/all\/themes\/tandem\/sass\/components\/_misc.scss}line{font-family:\00003452}}

I have a feeling this should be the cleaner comments for firecompass?

Any advice appreciated, and thanks for all your work on this great add-on!
D.

**Comment by FunkSugar** [comment]
i set debug_info to false and now it seems to work!

**Comment by is-already-taken** [comment]
Updated/edited.

You turn the config that produces the meta information used by FireCompass off and it works? Interesting.

On the debug_info: http://sass-lang.com/documentation/file.SASS_REFERENCE.html#debug_info-option

The output produced with the `firesass` option is not relevant for FireCompass, only the debug info (the original filename and line number in the comment above each rule).

Note that the FireSass plugin obviously has been abadoned: https://addons.mozilla.org/en-US/firefox/addon/firesass-for-firebug/ (today "`This add-on has been removed by its author.`")

You might remove the `firesass` config option but set `line_numbers` (see [the documentation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#line_numbers-option)) to true.

**Comment by FunkSugar** [comment]
FYI, here is my current .rb file 
http://pastebin.com/wqe7mWUn

Thanks,
D.

**Comment by clara80** [comment]
I didn't get firecompass to work in firefox. I see only css with line numbers, not scss. 
I tried a lot of different settings. 

Now I have in config.rb 
firecompass = true
sass_options = (environment == :development && firecompass == true) ? {:line_comments => true} : {}

Any idea?

**Comment by is-already-taken** [comment]
Can you please post an excerpt (e.g. starting from line 1, including the first two rules) of the generated `.css` file please, so that I can test them? 

Your config looks unnecessary complicated to me, why combining `environment` and your `firecompass` variable (which is not oficially supported by sass)?

Note that even if `line_comments = true` is present the generated CSS will not contain line comments if the folowing options are present: 
- `output_style = :compressed` (`:expanded`, `:nested` and `:compact` is OK)
- `environment = :production` (`:development` is OK)

Both will compress and remove debug information.

The comment line above the rule is crucial:

```
/* line 61, ../sass/main.scss */
body.has-js {
...
```

Can you please tell us which sass version you're using?
I assumed that in the past, but are you really using compass as frontend?

**Comment by is-already-taken** [comment]
@clara80: do you have any update on this?

**Comment by peterjlord** [comment]
Changing to :debug_info => false worked for me. As wasn't working.
sass_options = (environment == :development && firesass == true) ? {:debug_info => false} : {}

**Comment by clara80** [comment]
I'm sorry for my late reaction. I was out of office. 

@peterjlord I tried your suggestion, without success.

@is-already-taken 
Here are parts of my generated css; it looks strange. I use koala to compile.

<pre>
<code>
@charset "CP850";
@media -sass-debug-info{filename{font-family:file\:\/\/C\:\/xampp\/htdocs\/xx\/sites\/all\/themes\/xx\/sass\/_normalize\.scss}line{font-family:\0000333}}
footer,
header,
main,
nav,
section,
summary {
  display: block;
}
/* Correct `inline-block` display not defined in IE 8/9. */
@media -sass-debug-info{filename{font-family:file\:\/\/C\:\/xampp\/htdocs\/xx\/sites\/all\/themes\/xx\/sass\/_normalize\.scss}line{font-family:\0000340}}
audio,
canvas,
video {
  display: inline-block;
}
</code></pre>

The important lines from my current config.rb

<pre>
<code>
environment = :development
firesass = true
output_style = (environment == :development) ? :expanded : :nested
relative_assets = true
line_comments = true
sass_options = (environment == :development && firesass == true) ? {:debug_info => false} : {}
</code></pre>

**Comment by is-already-taken** [comment]
Hello.

The line comments containing the debug information are missing. Since you have a `line_comments` variable set to `true`, it might have todo with the other options - because they're conflicting. Please try to remove all those options except `line_comments`.

Please always make a `compass clean` before compiling because compass might not recompile if the source hasn't changed.

The debug information in this line

`@media -sass-debug-info{filename{font-family:file\:\/\/C\:\/xampp\/htdocs\/xx\/sites\/all\/themes\/xx\/sass\/_normalize\.scss}line{font-family:\0000333}}`

is not supported by FireCompass 0.2.

Please tell us which Compass version you are using: `compass -v`

**Comment by clara80** [comment]
Hello, 
I tried it with koala compiler (Compass 0.12.2)  and prepros compiler (can't find Compass Version) and started a new project with the same css pattern result as above.
I don't understand why in every css line is written "font-family".
